
name: Publish Sitemap

on:
  push:
    branches: [ main ]

jobs:
  ping:
    name: Ping Google
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP GET request
        run: curl https://www.google.com/ping?sitemap=https://solothought.com/sitemap.xml
